---
title: "Test Analysis"
author: "Kaitlin Rommelfanger"
date: "2025-12-05"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r Explore something}
library(readr)
library(tidyverse)

#removed the two reps where intake radicle length was 10 in excel prior to import, this length is impossible 

sprout <- read_csv("Sprouting Experiment/data/E1 LARA_AVGE intake experiment Fall 2022 - MasterData.csv")

sprout<-sprout%>%filter(`IntakeDate`!="11/7/22")#remove the one random intake on 11/7 

##replace the <0.01 with 0.005 (essentially <RL is changed to half of the reporting limit)
sprout$`IntakeRadicleLength-cm`[sprout$`IntakeRadicleLength-cm`=="<0.1"]<-0.005

#change all NA to 0, in intake radical length
sprout$`IntakeRadicleLength-cm`[is.na(sprout$`IntakeRadicleLength-cm`)] <- 0


#split the tray number and treatment type into two separate columns so I can plot separately 
sprout<-sprout%>%separate(`Tray ID`, into = c("Treatment","Tray Number"), sep = " ")

#write an if else statement to make sprouted or not 0 or 1
#sprouted-1
#not sprouted-0
sprout$sprouted<-ifelse(sprout$SproutDate=="NA",'0','1')

#made not sprouted NA instead of 0, so changing NA to 0 in sprouted column
sprout$sprouted[is.na(sprout$sprouted)]<-0

sprout$SiteID<-gsub("STEER Basin", "STEER", sprout$SiteID)


#filter the props by species
LARA<-sprout%>%filter(Species=="LARA")
AVGE<-sprout%>%filter(Species=="AVGE")


#going to remove an outlier in AVGE (likely typo)
AVGE<-AVGE%>%
  filter(PropaguleLength!=0.40)
#more outliers (likely typos too)
AVGE<-AVGE%>%
  filter(`Width-mm`!=1.3)
AVGE<-AVGE%>%
  filter(`Width-mm`!=1.5)
AVGE<-AVGE%>%
  filter(`Width-mm`!=1.7)

#remove outliers in LARA (likely errors)
LARA<-LARA%>%
  filter(`Width-mm`>=4)
LARA<-LARA%>%
  filter(`Width-mm`<=14)
LARA<-LARA%>%
  filter(Mass<=1.66)


#sprouted as numeric
AVGE$sprouted<-as.numeric(AVGE$sprouted)
LARA$sprouted<-as.numeric(LARA$sprouted)

#intake radicle length as numeric
AVGE$`IntakeRadicleLength-cm`<-as.numeric(AVGE$`IntakeRadicleLength-cm`)


#sproutdate and intake date as dates
sprout$SproutDate<-mdy(sprout$SproutDate)
sprout$IntakeDate<-mdy(sprout$IntakeDate)
sprout$RemovalDate<-mdy(sprout$RemovalDate)
```


```{r}

library(survival)
library(ggsurvfit)
library(survminer)


#For this analysis we need 
#censoring status: the values in this column are 1 = event happened, 0 = censored (or TRUE and FALSE).

    #this is the sprouted column that we made above, where if it sprotued 1, if       not sprotued 0

#time to event: from the start time (e.g., time of diagnosis) to the end time (the event happened or the last day of follow-up

  #to do this I am calculating the days until the props either sprouted, or were      removed

#using an if else statement to do this, 
sprout<-sprout%>%
  mutate(DaysUntilEvent=  #making a new column
  ifelse(
  is.na(sprout$SproutDate), #if there is an NA in sproutdate
  RemovalDate -IntakeDate,  #then going to subtract removal date
  SproutDate -IntakeDate )) #if there is anything but an NA, then subtract sprout date

#check to make sure my columns are numeric
str(sprout)
sprout$sprouted<-as.numeric(sprout$sprouted)

#separate the two species

LARA<-sprout%>%
  filter(Species=="LARA")

AVGE<-sprout%>%
  filter(Species=="AVGE")

#now we create the survival object using these two columns we created in sprout
LARAsurv_obj <- Surv(time = LARA$DaysUntilEvent, event = LARA$sprouted)
AVGEsurv_obj<-Surv(time = AVGE$DaysUntilEvent, event = AVGE$sprouted)

#Log Rank Test
LARAsurv <- survfit(LARAsurv_obj ~ Treatment, data = LARA)
AVGEsurv<- survfit(AVGEsurv_obj ~ Treatment, data = AVGE)

#plotting
LARAplot<-ggsurvplot(LARAsurv, data=LARA)

LARAplot

AVGEplot<-ggsurvplot(AVGEsurv, data=AVGE)
AVGEplot



LARAplot<-ggsurvplot(s2, data = df,
           size = 1,
           palette = c('#E7B800', '#2e9fdf'),
           censor.shape = '|', censor.size = 4,
           conf.int = TRUE,
           pval = TRUE,
           risk.table = TRUE,
           risk.table.col = 'strata',
           legend.labs = list('0' = 'No chemo', '1' = 'Chemo'),
           risk.table.height = 0.25,
           ggtheme = theme_bw())


#  Range Cay 
g_range <- ggsurvplot(
  fit_range,
  data = range_surv,
  conf.int = TRUE,
  pval = FALSE,
  risk.table = TRUE,
  risk.table.col = "strata",
  risk.table.height = 0.25,
  legend.title = "Treatment",
  legend.labs = c("DCLM", "LCDM", "LCLM"),
  palette = treatment_colors,
  title = "Range Cay",
  xlab = "Monitoring Date",
  ylab = "Survival Probability",
  ggtheme = theme_minimal(base_size = 14)
  
)


```

going to run a kaplin meyer curve analysis to analyze time until sprouting.. 
biostatssquid is a good source to walk through this analysis

The theory behind it all
https://biostatsquid.com/survival-time-analysis-easily-explained/
https://biostatsquid.com/kaplan-meier-curve/
https://biostatsquid.com/easy-log-rank-test/
https://biostatsquid.com/easy-cox-regression-for-survival-analysis/

the code (how to do it)
https://biostatsquid.com/easy-survival-analysis-r-tutorial/ 

another tutorial I like the first one better https://www.sthda.com/english/wiki/survival-analysis-basics

```{r Kaplin Meyer Survival Curve}
library(survival)
library(ggsurvfit)
library(survminer)
library(tidyverse)

#this is me stepping through the tutorial 
df <- survival::rotterdam

#censoring status: the values in this column are 1 = event happened, 0 = censored (or TRUE and FALSE). 

    #so in my case this would mean yes it sprouted, no it did not sprout


#time to event: from the start time (e.g., time of diagnosis) to the end time (the event happened or the last day of follow-up


df <- df %>% mutate(status = death)
table(df$status)
df <- df %>% mutate(dtime_yrs = dtime/365.25)
surv_obj <- Surv(time = df$dtime_yrs, event = df$status)


s1 <- survfit(surv_obj ~ 1, data = df)
summary(s1)

#plot 
km_curve <- ggsurvfit(s1, linewidth = 1) +
  labs(x = 'Years', y = 'Overall survival') +
  add_confidence_interval() +
  add_risktable() +
  scale_ggsurvfit() + 
  coord_cartesian(xlim = c(0, 8))

km_curve

s2 <- survfit(surv_obj ~ chemo, data = df)
ggsurvplot(s2, data = df,
           size = 1,
           palette = c('#E7B800', '#2e9fdf'),
           censor.shape = '|', censor.size = 4,
           conf.int = TRUE,
           pval = TRUE,
           risk.table = TRUE,
           risk.table.col = 'strata',
           legend.labs = list('0' = 'No chemo', '1' = 'Chemo'),
           risk.table.height = 0.25,
           ggtheme = theme_bw())

#log rank test
logrankres_chemo <- survdiff(Surv(dtime_yrs, status) ~ chemo, data = df)
logrankres_chemo

logrankres_hor <- survdiff(Surv(dtime_yrs, status) ~ hormon, data = df)
logrankres_hor


#cox test
cox_res <- coxph(Surv(dtime_yrs, status) ~ hormon + chemo + size + er + pgr + nodes + meno + grade + age, data = df)
cox_res
```
